# Generated by Django 4.0.4 on 2022-04-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Balance'),
        ),
    ]
