# Generated by Django 4.0.4 on 2022-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0004_round_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='color',
            field=models.CharField(max_length=30, null=True, verbose_name='Random color'),
        ),
    ]
