# Generated by Django 4.0.4 on 2022-04-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0007_statisticrouletteuser_win_value_all'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticrouletteuser',
            old_name='bet_value_all',
            new_name='bet_value',
        ),
        migrations.RenameField(
            model_name='statisticrouletteuser',
            old_name='win_value_all',
            new_name='win_value',
        ),
    ]
