# Generated by Django 4.0.4 on 2022-04-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0008_rename_bet_value_all_statisticrouletteuser_bet_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticrouletteuser',
            name='color',
            field=models.CharField(max_length=30, null=True, verbose_name='Bet color'),
        ),
        migrations.AlterField(
            model_name='statisticrouletteuser',
            name='bet_value',
            field=models.IntegerField(null=True, verbose_name='Bet value'),
        ),
        migrations.AlterField(
            model_name='statisticrouletteuser',
            name='win_value',
            field=models.IntegerField(null=True, verbose_name='Win value'),
        ),
    ]
