# Generated by Django 4.0.4 on 2022-05-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0009_statisticrouletteuser_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(max_length=32, null=True, verbose_name='User token'),
        ),
    ]
