# Generated by Django 4.0.4 on 2022-05-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0010_profile_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time')),
                ('sender', models.CharField(max_length=255, verbose_name='Sender name')),
                ('recipient', models.CharField(max_length=255, verbose_name='Recipient name')),
                ('value', models.IntegerField(verbose_name='Value of transfer')),
            ],
        ),
    ]
