# Generated by Django 4.0.4 on 2022-05-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0011_transfertransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticrouletteuser',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='Time'),
        ),
    ]
